version: "3.9"

services:
  franchise-app:
    build:
      context: ./Franquicia
      dockerfile: deployment/Dockerfile
    container_name: franchise-app
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: ${MONGO_URI}
    networks:
      - franchise-net

networks:
  franchise-net:
    driver: bridge

