server:
  port: 8080
spring:
  application:
    name: "Franchise"
  devtools:
    add-properties: false
  data:
    mongodb:
      uri: ${MONGO_URI}
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
